In [1]:
# Import libaries

from bs4 import BeautifulSoup
import pandas as pd
import requests
import numpy as np

In [2]:
final_list = []

# Skytrax URL
url = 'https://www.airlinequality.com/airline-reviews/jetstar-airways/?sortby=post_date%3ADesc&pagesize=100'

# Request URL
response = requests.get(url)

# Create Soup
soup = BeautifulSoup(response.content, 'lxml')

# For loop for HTML
for idx, review in enumerate(soup.find_all('div',{'class':"review-stats"})):
    
    # Create a empty dictionary to contain columns and values
    review_dict = dict()
    
    # Values that is in star fill
    names = review.find_all('td', class_='review-rating-header')[::-1]
    ratings = review.find_all('td', class_='stars')[::-1]
    
    for name, rating in zip(names[1:], ratings):
        review_dict[name.text] = rating.find_all(class_='fill')[-1].text
    
    # Author, Date, Overall_rating,Text_content, Recommended
    review_dict['Author'] = soup.find_all(itemprop='name')[idx+1].text
    review_dict['Date'] = soup.find_all(itemprop='datePublished')[::2][idx].attrs['content']
    review_dict['Overall_rating'] = soup.find_all('div',{'itemprop':'reviewRating'})[idx].find(itemprop="ratingValue").text
    review_dict['text_content'] = soup.find_all('div',class_='text_content')[idx].text
    review_dict['Recommended'] = soup.find_all('div',{'class':"review-stats"})[idx].find_all('tr')[-1].find_all('td')[-1].text
        
    # Type of Traveller
    try:
        review.find('td',{'class':'review-rating-header type_of_traveller'}).text is not None
        review_dict['traveller_type'] = soup.find_all('td',{'class':'review-rating-header type_of_traveller'})[idx].fetchNextSiblings()[0].text
    
    except:
        review_dict['traveller_type'] = np.nan
    
    # Seat type
    try:
        review.find('td',{'class':'review-rating-header cabin_flown'}).text is not None
        review_dict['seat_type'] = soup.find_all('td',{'class':'review-rating-header cabin_flown'})[idx].fetchNextSiblings()[0].text
    
    except:
        review_dict['seat_type'] = np.nan
    
    
    # Append dictionary into a list
    final_list.append(review_dict)

# Create DataFrame
df = pd.DataFrame(final_list)
df['airline'] = 'jetstar airways'

# Save to CSV
df.to_csv('Data/jetstar_airways.csv',index=False)

In [3]:
# Sanity check
df

,Value For Money,Ground Service,Cabin Staff Service,Seat Comfort,Author,Date,Overall_rating,text_content,Recommended,traveller_type,seat_type,Wifi & Connectivity,Inflight Entertainment,Food & Beverages,airline
0,1,1,1,1,Saul Geffen,2020-05-06,1,Not Verified | Brisbane to Melbourne. Just li...,no,Solo Leisure,Economy Class,NaN,NaN,NaN,jetstar airways
1,1,NaN,NaN,NaN,E Marcerios,2020-05-05,1,✅ Trip Verified | My friend and I were travel...,no,Couple Leisure,Economy Class,NaN,NaN,NaN,jetstar airways
2,1,1,1,1,Chris Pokrzywa,2020-04-27,1,✅ Trip Verified | I'm absolutely appalled Jets...,no,Couple Leisure,Business Class,NaN,NaN,NaN,jetstar airways
3,1,1,1,1,Caryn Jervis,2020-04-21,1,✅ Trip Verified | Extremely poor customer serv...,no,Solo Leisure,Economy Class,NaN,NaN,NaN,jetstar airways
4,1,1,NaN,NaN,A Gurten,2020-04-15,1,✅ Trip Verified | I am very disappointed with...,no,Family Leisure,Economy Class,NaN,NaN,NaN,jetstar airways
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,1,1,NaN,NaN,Paul Simonides,2019-12-08,1,Not Verified | Adelaide to Sydney. I've been ...,no,Family Leisure,Economy Class,NaN,NaN,NaN,jetstar airways
96,1,1,1,1,Victor Hew,2019-12-07,1,✅ Trip Verified | Sydney to Melbourne. If the...,no,Solo Leisure,Economy Class,NaN,NaN,NaN,jetstar airways
97,3,4,3,2,Ian Fleming,2019-12-06,2,✅ Trip Verified | Newcastle to Melbourne. Boo...,no,Couple Leisure,Economy Class,NaN,NaN,NaN,jetstar airways
98,1,1,2,1,J Ryd,2019-12-03,1,Not Verified | Queenstown to Sydney. My fligh...,no,Solo Leisure,Economy Class,1,1,1,jetstar airways
99,1,1,1,1,D Varunic,2019-12-02,1,✅ Trip Verified | Sunshine Coast to Sydney. T...,no,Business,Economy Class,1,1,1,jetstar airways