In [1]:
# Import libaries

from bs4 import BeautifulSoup
import pandas as pd
import requests
import numpy as np

In [2]:
final_list = []

# Skytrax URL
url = 'https://www.airlinequality.com/airline-reviews/jeju-air/?sortby=post_date%3ADesc&pagesize=20'

# Request URL
response = requests.get(url)

# Create Soup
soup = BeautifulSoup(response.content, 'lxml')

# For loop for HTML
for idx, review in enumerate(soup.find_all('div',{'class':"review-stats"})):
    
    # Create a empty dictionary to contain columns and values
    review_dict = dict()
    
    # Values that is in star fill
    names = review.find_all('td', class_='review-rating-header')[::-1]
    ratings = review.find_all('td', class_='stars')[::-1]
    
    for name, rating in zip(names[1:], ratings):
        review_dict[name.text] = rating.find_all(class_='fill')[-1].text
    
    # Author, Date, Overall_rating,Text_content, Recommended
    review_dict['Author'] = soup.find_all(itemprop='name')[idx+1].text
    review_dict['Date'] = soup.find_all(itemprop='datePublished')[::2][idx].attrs['content']
    review_dict['Overall_rating'] = soup.find_all('div',{'itemprop':'reviewRating'})[idx].find(itemprop="ratingValue").text
    review_dict['text_content'] = soup.find_all('div',class_='text_content')[idx].text
    review_dict['Recommended'] = soup.find_all('div',{'class':"review-stats"})[idx].find_all('tr')[-1].find_all('td')[-1].text
        
    # Type of Traveller
    try:
        review.find('td',{'class':'review-rating-header type_of_traveller'}).text is not None
        review_dict['traveller_type'] = soup.find_all('td',{'class':'review-rating-header type_of_traveller'})[idx].fetchNextSiblings()[0].text
    
    except:
        review_dict['traveller_type'] = np.nan
    
    # Seat type
    try:
        review.find('td',{'class':'review-rating-header cabin_flown'}).text is not None
        review_dict['seat_type'] = soup.find_all('td',{'class':'review-rating-header cabin_flown'})[idx].fetchNextSiblings()[0].text
    
    except:
        review_dict['seat_type'] = np.nan
    
    
    # Append dictionary into a list
    final_list.append(review_dict)

# Create DataFrame
df = pd.DataFrame(final_list)
df['airline'] = 'jeju air'

# Save to CSV
df.to_csv('Data/jeju_air.csv',index=False)

In [3]:
# Sanity check
df.head()

,Value For Money,Ground Service,Cabin Staff Service,Seat Comfort,Author,Date,Overall_rating,text_content,Recommended,traveller_type,seat_type,Food & Beverages,Inflight Entertainment,Wifi & Connectivity,airline
0,4,5,5,4,V Gallera,2020-02-12,8,✅ Trip Verified | Clark to Seoul. Smooth flig...,yes,Family Leisure,Economy Class,NaN,NaN,NaN,jeju air
1,1,1,5,1,N Fan,2020-01-21,1,✅ Trip Verified | Jeju to Hong Kong. The airp...,no,Solo Leisure,Economy Class,NaN,NaN,NaN,jeju air
2,2,1,2,3,Mei ling Chan,2019-11-21,1,✅ Trip Verified | Jeju to Seoul. I realize my...,no,Solo Leisure,Economy Class,NaN,NaN,NaN,jeju air
3,1,1,NaN,NaN,A Linton,2019-11-17,1,Not Verified | My wife was flying in from the...,no,Family Leisure,Economy Class,NaN,NaN,NaN,jeju air
4,3,4,4,2,Charlie Norton,2019-10-02,7,Not Verified | Osaka Kansai to Seoul. Very goo...,yes,Family Leisure,Economy Class,3,NaN,NaN,jeju air