In [1]:
# Import libaries

from bs4 import BeautifulSoup
import pandas as pd
import requests
import numpy as np

In [2]:
final_list = []

# Skytrax URL
url = 'https://www.airlinequality.com/airline-reviews/ana-all-nippon-airways/?sortby=post_date%3ADesc&pagesize=20'

# Request URL
response = requests.get(url)

# Create Soup
soup = BeautifulSoup(response.content, 'lxml')

# For loop for HTML
for idx, review in enumerate(soup.find_all('div',{'class':"review-stats"})):
    
    # Create a empty dictionary to contain columns and values
    review_dict = dict()
    
    # Values that is in star fill
    names = review.find_all('td', class_='review-rating-header')[::-1]
    ratings = review.find_all('td', class_='stars')[::-1]
    
    for name, rating in zip(names[1:], ratings):
        review_dict[name.text] = rating.find_all(class_='fill')[-1].text
    
    # Author, Date, Overall_rating,Text_content, Recommended
    review_dict['Author'] = soup.find_all(itemprop='name')[idx+1].text
    review_dict['Date'] = soup.find_all(itemprop='datePublished')[::2][idx].attrs['content']
    review_dict['Overall_rating'] = soup.find_all('div',{'itemprop':'reviewRating'})[idx].find(itemprop="ratingValue").text
    review_dict['text_content'] = soup.find_all('div',class_='text_content')[idx].text
    review_dict['Recommended'] = soup.find_all('div',{'class':"review-stats"})[idx].find_all('tr')[-1].find_all('td')[-1].text
        
    # Type of Traveller
    try:
        review.find('td',{'class':'review-rating-header type_of_traveller'}).text is not None
        review_dict['traveller_type'] = soup.find_all('td',{'class':'review-rating-header type_of_traveller'})[idx].fetchNextSiblings()[0].text
    
    except:
        review_dict['traveller_type'] = np.nan
    
    # Seat type
    try:
        review.find('td',{'class':'review-rating-header cabin_flown'}).text is not None
        review_dict['seat_type'] = soup.find_all('td',{'class':'review-rating-header cabin_flown'})[idx].fetchNextSiblings()[0].text
    
    except:
        review_dict['seat_type'] = np.nan
    
    
    # Append dictionary into a list
    final_list.append(review_dict)

# Create DataFrame
df = pd.DataFrame(final_list)
df['airline'] = 'ana all nippon airways'

# Save to CSV
df.to_csv('Data/ana.csv',index=False)

In [3]:
# Sanity check
df

,Value For Money,Ground Service,Inflight Entertainment,Food & Beverages,Cabin Staff Service,Seat Comfort,Author,Date,Overall_rating,text_content,Recommended,traveller_type,seat_type,Wifi & Connectivity,airline
0,5,5,4,5,5,5,Larry Silverstein,2020-04-11,10,✅ Trip Verified | New York to Tokyo with ANA....,yes,Couple Leisure,Business Class,NaN,ana all nippon airways
1,5,4,5,5,5,4,Ken Inaba,2020-04-01,9,✅ Trip Verified | Fukuoka to Vancouver via T...,yes,Solo Leisure,Economy Class,NaN,ana all nippon airways
2,5,5,5,5,5,5,Michelle Massey,2020-03-25,10,✅ Trip Verified | Narita to Perth. ANA kept us...,yes,Couple Leisure,Business Class,5,ana all nippon airways
3,5,5,5,5,5,4,Jarosław Miazga,2020-02-25,10,✅ Trip Verified | A very enjoyable flight. I ...,yes,Solo Leisure,Economy Class,NaN,ana all nippon airways
4,5,5,5,5,5,5,Mohamed Elsamak,2020-02-24,10,✅ Trip Verified | Kuala Lumpur to Los Angeles...,yes,Solo Leisure,Economy Class,5,ana all nippon airways
5,5,5,4,4,5,5,Amanda Lockett,2020-01-29,10,Not Verified | ANA is the best airline I have...,yes,Family Leisure,Economy Class,NaN,ana all nippon airways
6,5,4,5,4,5,5,Elizabeth Anderson,2020-01-27,9,✅ Trip Verified | Bangkok to Tokyo. So I have...,yes,Family Leisure,Economy Class,NaN,ana all nippon airways
7,3,2,4,5,4,5,S Wang,2020-01-16,7,✅ Trip Verified | Houston to Singapore via Na...,yes,Business,Premium Economy,NaN,ana all nippon airways
8,5,3,5,5,4,4,W Ellis,2020-01-07,7,✅ Trip Verified | Haneda to Kuala Lumpur with ...,yes,Couple Leisure,Economy Class,NaN,ana all nippon airways
9,1,2,2,2,3,2,Justin Colebrissi,2020-01-05,3,✅ Trip Verified | Ho Chi Minh City to Seattle...,no,Family Leisure,Economy Class,NaN,ana all nippon airways
10,4,4,2,2,4,5,H Green,2019-12-25,6,✅ Trip Verified | Tokyo to Perth. We found th...,no,Couple Leisure,Economy Class,NaN,ana all nippon airways
11,5,5,5,5,5,5,Trung Hoang,2019-12-17,10,✅ Trip Verified | Los Angeles to Ho Chi Minh ...,yes,Family Leisure,Economy Class,5,ana all nippon airways
12,5,5,4,5,5,5,L Tran,2019-12-10,10,✅ Trip Verified | Tokyo to New York. Excellent...,yes,Solo Leisure,First Class,4,ana all nippon airways
13,5,5,4,4,5,4,L Tran,2019-12-01,8,"✅ Trip Verified | Tokyo to Beijing. First, the...",yes,Solo Leisure,Business Class,NaN,ana all nippon airways
14,5,5,4,5,5,5,L Tran,2019-11-29,10,✅ Trip Verified | New York to Tokyo Narita. A...,yes,Solo Leisure,Business Class,NaN,ana all nippon airways
15,5,5,5,1,1,5,James Swayngim,2019-11-15,5,✅ Trip Verified | Los Angeles to Haneda was f...,no,Family Leisure,Economy Class,NaN,ana all nippon airways
16,5,5,4,5,5,4,Randall Payne,2019-11-11,9,Not Verified | Bangkok to Houston via Tokyo. ...,yes,Solo Leisure,Economy Class,NaN,ana all nippon airways
17,4,5,5,5,5,3,Q Morse,2019-11-01,9,Not Verified | Los Angeles to Bangkok via Tok...,yes,Couple Leisure,Economy Class,3,ana all nippon airways
18,3,NaN,NaN,NaN,NaN,NaN,A Kirk,2019-10-30,1,✅ Trip Verified | I had a domestic flight fro...,no,Couple Leisure,Economy Class,NaN,ana all nippon airways
19,1,1,NaN,NaN,5,3,Rose Jaffurs,2019-10-30,3,✅ Trip Verified | \r\nHonolulu to Tokyo Hane...,no,Solo Leisure,Business Class,NaN,ana all nippon airways