In [1]:
# Import libaries

from bs4 import BeautifulSoup
import pandas as pd
import requests
import numpy as np

In [2]:
final_list = []

# Skytrax URL
url = 'https://www.airlinequality.com/airline-reviews/myanmar-national-airlines/?sortby=post_date%3ADesc&pagesize=20'

# Request URL
response = requests.get(url)

# Create Soup
soup = BeautifulSoup(response.content, 'lxml')

# For loop for HTML
for idx, review in enumerate(soup.find_all('div',{'class':"review-stats"})):
    
    # Create a empty dictionary to contain columns and values
    review_dict = dict()
    
    # Values that is in star fill
    names = review.find_all('td', class_='review-rating-header')[::-1]
    ratings = review.find_all('td', class_='stars')[::-1]
    
    try:
        for name, rating in zip(names[1:], ratings):
            review_dict[name.text] = rating.find_all(class_='fill')[-1].text
    except:
        review_dict[name.text] = np.nan
    
    # Author, Date, Overall_rating,Text_content, Recommended
    review_dict['Author'] = soup.find_all(itemprop='name')[idx+1].text
    review_dict['Date'] = soup.find_all(itemprop='datePublished')[::2][idx].attrs['content']
    review_dict['text_content'] = soup.find_all('div',class_='text_content')[idx].text
    review_dict['Recommended'] = soup.find_all('div',{'class':"review-stats"})[idx].find_all('tr')[-1].find_all('td')[-1].text
        
    # Type of Traveller
    try:
        review.find('td',{'class':'review-rating-header type_of_traveller'}).text is not None
        review_dict['traveller_type'] = soup.find_all('td',{'class':'review-rating-header type_of_traveller'})[idx].fetchNextSiblings()[0].text
    
    except:
        review_dict['traveller_type'] = np.nan
    
    # Seat type
    try:
        review.find('td',{'class':'review-rating-header cabin_flown'}).text is not None
        review_dict['seat_type'] = soup.find_all('td',{'class':'review-rating-header cabin_flown'})[idx].fetchNextSiblings()[0].text
    
    except:
        review_dict['seat_type'] = np.nan
    
    try:
        review_dict['Overall_rating'] = soup.find_all('div',{'itemprop':'reviewRating'})[idx].find(itemprop="ratingValue").text
    
    except:
        review_dict['Overall_rating'] = np.nan
    
    
    # Append dictionary into a list
    final_list.append(review_dict)

# Create DataFrame
df = pd.DataFrame(final_list)
df['airline'] = 'myanmar national airlines'

# Save to CSV
df.to_csv('Data/myanmar.csv',index=False)

In [3]:
# Sanity check
df.tail()

,Value For Money,Ground Service,Food & Beverages,Cabin Staff Service,Seat Comfort,Author,Date,text_content,Recommended,traveller_type,seat_type,Overall_rating,Wifi & Connectivity,Inflight Entertainment,airline
6,5,5,5,5,5,Min Htet,2017-12-08,✅ Trip Verified | Yangon to Mandalay. Lounge ...,yes,Solo Leisure,Business Class,10,5,5,myanmar national airlines
7,5,5,5,5,5,Even Nordhagen,2017-06-06,✅ Verified Review | Singapore to Yangon. I di...,yes,Solo Leisure,Economy Class,10,NaN,5,myanmar national airlines
8,3,4,4,5,4,A Green,2017-05-05,"✅ Verified Review | Very happy with my trip, ...",yes,Solo Leisure,Economy Class,10,NaN,NaN,myanmar national airlines
9,2,2,4,5,4,F Marks,2017-02-05,✅ Verified Review | Flew the quick 45 minute f...,yes,Couple Leisure,Economy Class,8,1,1,myanmar national airlines
10,5,4,3,4,4,An Thung,2016-08-15,✅ Verified Review | I traveled Yangon to Sing...,yes,Solo Leisure,Economy Class,7,4,4,myanmar national airlines

In [4]:
df.head()

,Value For Money,Ground Service,Food & Beverages,Cabin Staff Service,Seat Comfort,Author,Date,text_content,Recommended,traveller_type,seat_type,Overall_rating,Wifi & Connectivity,Inflight Entertainment,airline
0,4,4,5,5,4,Michael Schade,2019-05-13,✅ Trip Verified | Singapore to Thandwe via Yan...,yes,Solo Leisure,Economy Class,10,NaN,NaN,myanmar national airlines
1,4,2,4,3,5,Thomas van Woerkom,2019-03-21,✅ Trip Verified | Yangon to Heho with Myanmar ...,yes,Couple Leisure,Economy Class,8,NaN,NaN,myanmar national airlines
2,5,5,5,5,5,G. Stoykovich,2018-12-28,"✅ Trip Verified | Loikaw to Yangon. Quick, ef...",yes,Couple Leisure,Economy Class,10,NaN,NaN,myanmar national airlines
3,1,1,NaN,3,3,Wai Lynn Htun,2018-10-04,✅ Trip Verified | Yangon to Mandalay. Aircraf...,no,Business,Economy Class,1,NaN,NaN,myanmar national airlines
4,4,5,4,5,4,M Andrews,2018-06-11,✅ Trip Verified | The flight was about one hou...,yes,Family Leisure,Economy Class,9,NaN,NaN,myanmar national airlines